/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dondish.specatles;

import io.reactivex.Flowable;
import io.reactivex.Observable;
import io.vertx.core.Closeable;
import io.vertx.core.Vertx;
import io.vertx.core.eventbus.EventBus;
import io.vertx.core.eventbus.MessageConsumer;
import io.vertx.reactivex.FlowableHelper;
import io.vertx.reactivex.ObservableHelper;

import javax.annotation.Nonnull;
import java.util.concurrent.CompletableFuture;

/**
 * The basic broker interface to communicate with other modules
 */
public interface Broker extends Closeable {

    /**
     * The vertx instance
     * @return The vertx instance
     */
    Vertx vertx();

    /**
     * The eventbus instance
     * @return The eventbus instance
     */
    EventBus eventBus();

    /**
     * Handles single or multiple events
     * @param events the event names to handle
     * @return The vertx message consumer to consume events
     */
    CompletableFuture<MessageConsumer<byte[]>> on(@Nonnull final String... events) throws Throwable;

    /**
     * Handles single or multiple events and returns a reactive stream
     * @param events the event names to handle
     * @return A vertx reactive stream
     */
    default CompletableFuture<Flowable<byte[]>> flow(@Nonnull final String... events) throws Throwable {
        return on(events).thenApply(a -> FlowableHelper.toFlowable(a.bodyStream()));
    }

    /**
     * Handles single or multiple events and returns a reactive stream
     * @param events the event names to handle
     * @return A vertx reactive stream
     */
    default CompletableFuture<Observable<byte[]>> observe(@Nonnull final String... events) throws Throwable {
        return on(events).thenApply(a -> ObservableHelper.toObservable(a.bodyStream()));
    }

    CompletableFuture<Void> publish(@Nonnull final String event, @Nonnull final byte[] data);
}